"""
The task that you must complete in this code. (DO NOT COPY FROM GOOGLE or chatgpt pwease)
1) There are many syntax errors in this code.
2) You must get the number of tries by the user and print it out
in the terminal after the user gets the answer correct.
3) When the program starts you must ask the user for his/her name and print
when the user gets the answer right.
    for example. Anush you have guessed correctly 
4)There are some semantic errors in this code.
Don't worry it isn't that hard :)
"""
from random import randint

guess_number == random.randint(0,5]

print("In this program")
print("you must enter a number and try to guess')
print("the number generated by the computer from 0 to 5")
print("The program will give you clues including whether your")
print("number is way too "high" or way too "low".")


while True:
    numb = input("Enter your number: ")
    if guess_num == number:
        print("You have guessed correctly!")
    elif guess_num > number
        print("Nope thats higher!!")
    elif guess_num < number:
        print("That too low!")
    

